package com.example.batteryrisk.service;

import com.example.batteryrisk.domain.Analysis;
import com.example.batteryrisk.dto.MultiAgentDto;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * 자동 브리핑의 <b>평가 저장과 브리핑 저장을 한 트랜잭션으로 원자화</b>한다.
 *
 * <p>배경: 자동 경로는 {@code MultiAgentOrchestrationService.generate()}가
 * {@code procurement_risk_assessments}를, {@code AiBriefingService.recordAutoGenerated()}가
 * {@code ai_briefings}를 각각 {@code JdbcTemplate}로 즉시 auto-commit했다. 두 저장이 아무
 * 트랜잭션에도 안 묶여 있어, 한쪽만 커밋되면 <b>"브리핑은 있는데 평가가 없는"</b>(또는 반대)
 * 반쪽 상태가 남았다(실측 2건). 그 반쪽 상태는 대시보드 KPI를 어긋나게 한다 — 사건 수
 * (평가 기준)와 브리핑 수가 달라진다.
 *
 * <p>여기서 두 저장을 하나의 {@link Transactional}로 감싸, 둘 중 하나라도 실패하면 함께 롤백돼
 * 항상 "둘 다 있거나 둘 다 없거나"가 되게 한다. 두 저장 모두 JdbcTemplate이라 활성 트랜잭션에
 * 참여하므로(DataSourceUtils), 이 메서드 안에서 예외가 나면 assessment INSERT까지 되돌려진다.
 *
 * <p><b>왜 별도 빈인가</b>: Spring 프록시는 같은 클래스 내부 호출(self-invocation)에는
 * {@code @Transactional}을 적용하지 않는다. {@link AnalysisService}가 이 빈을 주입해 호출해야
 * 트랜잭션이 실제로 걸린다.
 *
 * <p><b>트레이드오프</b>: {@code generate()}의 FastAPI/LLM 호출이 트랜잭션 안에서 일어나 그동안
 * DB 커넥션을 쥔다. 자동 경로는 수집 스케줄러 기반(기본 off)이라 처리량이 낮아 감수한다.
 */
@Service
public class AutoBriefingWriter {

    private final MultiAgentOrchestrationService multiAgentOrchestrationService;
    private final AiBriefingService aiBriefingService;

    public AutoBriefingWriter(
            MultiAgentOrchestrationService multiAgentOrchestrationService,
            AiBriefingService aiBriefingService) {
        this.multiAgentOrchestrationService = multiAgentOrchestrationService;
        this.aiBriefingService = aiBriefingService;
    }

    /**
     * 평가(generate)와 브리핑(recordAutoGenerated)을 한 트랜잭션으로 저장한다. 예외가 나면
     * 전체 롤백 — 반쪽 저장을 남기지 않는다. 예외는 호출부({@link AnalysisService})가 흡수해
     * 분석 생성 자체는 막지 않는다.
     */
    @Transactional
    public void generateAndRecord(
            MultiAgentDto.GenerateRequest request, Analysis analysis,
            String erpMaterialId, String erpSupplierId, String materialCategory) {
        MultiAgentDto.Response response = multiAgentOrchestrationService.generate(request);
        aiBriefingService.recordAutoGenerated(
                analysis, erpMaterialId, erpSupplierId, materialCategory, response);
    }
}
