-- [surin 병합·화해] documents.document_type CHECK를 merge/surin 두 taxonomy의 합집합으로 확장(무손실).
-- merge V1: CONTRACT/PURCHASE_ORDER/SPECIFICATION/CERTIFICATE/OTHER
-- surin V1: LTA/PURCHASE_GUIDELINE/SUPPLIER_EVALUATION/QUALITY_CERTIFICATE/REGULATION/TECHNICAL_SPEC
ALTER TABLE documents DROP CONSTRAINT ck_document_type;
ALTER TABLE documents ADD CONSTRAINT ck_document_type CHECK (document_type IN (
    'CONTRACT', 'PURCHASE_ORDER', 'SPECIFICATION', 'CERTIFICATE', 'OTHER',
    'LTA', 'PURCHASE_GUIDELINE', 'SUPPLIER_EVALUATION', 'QUALITY_CERTIFICATE', 'REGULATION', 'TECHNICAL_SPEC'
));
