-- 회원가입 시 개인정보 수집·이용 동의 이력. 규제 가이드 ①(회원가입 시 개인정보 수집 및 이용 동의) 대응.
-- users 컬럼이 아니라 별도 테이블로 두어 동의 유형별 이력과 동의 시각을 감사 추적할 수 있게 한다.
-- 향후 선택 동의 항목이 늘어나도 스키마 변경 없이 행 추가만으로 확장된다.

CREATE TABLE user_consents (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    consent_type VARCHAR(40) NOT NULL,
    agreed       BOOLEAN NOT NULL,
    agreed_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_user_consents_type
        CHECK (consent_type IN ('PRIVACY_REQUIRED', 'MARKETING_OPTIONAL'))
);

CREATE INDEX idx_user_consents_user_id ON user_consents (user_id);

COMMENT ON TABLE user_consents IS '회원가입 개인정보 수집·이용 동의 이력(필수/선택).';
COMMENT ON COLUMN user_consents.consent_type IS 'PRIVACY_REQUIRED(필수 개인정보 수집·이용) / MARKETING_OPTIONAL(선택 이벤트·뉴스 수신).';
COMMENT ON COLUMN user_consents.agreed IS '해당 동의 유형에 대한 동의 여부.';
